# WM8505 codec presents L/R reversed; swap for every ALSA client

pcm.!default {
    type plug
    slave.pcm {
        type route
        slave.pcm "hw:0,0"
        ttable.0.1 1
        ttable.1.0 1
    }
}

ctl.!default {
    type hw
    card 0
}
